"""create data

Revision ID: 0a7782ab9721
Revises: 
Create Date: 2021-05-28 22:44:13.099707

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a7782ab9721'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('obat', sa.Column('kondisi', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('obat', 'kondisi')
    # ### end Alembic commands ###
